name: Discord定时任务

on:
  push: 
    branches:
      - main

  schedule:
    - cron: "2 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run index.js 
        run: 
          node ./index.js


